import { cloneDefaultElementStyles } from './figureElements'
import { DEFAULT_ELEMENT_POSITIONS } from './mapRenderer'
import type { AnnotationDefaults, FigureSettings } from './types'
import { DEFAULT_COLOR_RAMP_BY_USE } from './colorRamps'

export function createDefaultFigureSettings(): FigureSettings {
  return {
    orientation: 'landscape',
    dryDepth: 0,
    assessmentLineInterval: 1,
    assessmentLineColor: '#d92d20',
    assessmentLineWidth: 2,
    showAssessmentLines: true,
    showAssessmentLabels: true,
    assessmentLabelColor: '#172b3a',
    assessmentLabelFontSize: 18,
    assessmentLabelOffset: 28,
    assessmentLabelSide: 'alternate',
    differenceOutlineColor: '#111111',
    differenceOutlineWidth: 1.5,
    differenceOutlinePattern: 'solid',
    showDifferenceOutlines: true,
    showWetDry: true,
    showOverlays: true,
    showTitle: true,
    showLegend: true,
    showNorth: true,
    showScale: true,
    showWetDryKey: true,
    titleTemplate:
      '{type} - {baseline}: {baselineRun} vs {comparison}: {comparisonRun}',
    legendBound: null,
    legendInterval: null,
    differenceRamp: DEFAULT_COLOR_RAMP_BY_USE.wseDifference,
    legendFontSize: 19,
    newlyWetColor: '#2cc88b',
    newlyDryColor: '#e97768',
    basemapOpacity: 0.72,
    rotation: 0,
    zoom: 1,
    panX: 0,
    panY: 0,
    centerlineStationing: {
      visible: false,
      showMinorTicks: true,
      showMajorTicks: true,
      showLabels: true,
      minorInterval: 25,
      majorInterval: 100,
      labelInterval: 100,
      rangeStart: null,
      rangeEnd: null,
      minorTickLength: 10,
      majorTickLength: 18,
      minorLineWidth: 1.25,
      majorLineWidth: 2,
      tickSide: 'both',
      tickColor: '#d92d20',
      labelColor: '#172b3a',
      labelFontSize: 18,
      labelOffset: 25,
      labelSide: 'auto',
      labelOrientation: 'horizontal',
      labelHalo: true,
      prefix: '',
      decimalPlaces: 0,
      showEndpoints: false,
      showDirectionArrow: false,
      overrides: {},
    },
    elementPositions: structuredClone(DEFAULT_ELEMENT_POSITIONS),
    elementStyles: cloneDefaultElementStyles(),
  }
}

export function createDefaultAnnotationSettings(): AnnotationDefaults {
  return {
    text: 'Note',
    color: '#b42318',
    fillColor: '#ffffff',
    lineWidth: 3,
    fontSize: 20,
    rotation: 0,
    dashed: false,
    background: true,
    resultField: 'summary',
  }
}
